# Generated by Django 5.2 on 2025-09-03 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0002_plantacuidador_status_planta_plantahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantahistorico',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_alterados', to=settings.AUTH_USER_MODEL),
        ),
    ]
