# Generated by Django 5.2 on 2026-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0003_plantahistorico_usuario_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantacuidador',
            name='idade',
        ),
        migrations.AlterField(
            model_name='plantacuidador',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'REVISÃO'), ('APROVADO', 'APROVADO'), ('CORRECAO', 'CORREÇÃO')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantacuidador',
            name='status_planta',
            field=models.CharField(choices=[('VIVA', 'VIVA'), ('MORTA', 'MORTA'), ('REPLANTADA', 'REPLANTADA')], default='VIVA', max_length=20),
        ),
    ]
