# Generated by Django 5.2 on 2026-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0004_remove_plantacuidador_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COLAB', 'Colaborador')], default='COLAB', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantacuidador',
            name='numero_registro',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
